### ISSUE TITLE
Can this be installed globally?

### ISSUE THREAD

**Issue by davestewart** [amazingSurge/frontend-starter-kit#1]
Hello,

I just found this after googling for a better way to package and release jQuery plugins, seeing all your jQuery plugins, then finding this.

I love the amount of effort that has been put into this, but not sure I want to increase the size of my jQuery plugin repositories with ALL the functionality available here.

Is there any way this can be installed globally, then individual repositories published locally?

Thanks again,
Dave

**Comment by amazingSurge** [comment]
Hi Dave,
We are working on rewrite our jquery plugins. It will comes with a plugin-cli tool when it's release that is installed globally.
Regards,
JimbaCheng
